name: Becoming Man
favicon: null
layout_spectrum: 0.9681219458580017
typography_spectrum: 0.16588335647247732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05202078982256353
  lightness: 0.915981219150126
  saturation: 0.9506778866052628
  rhythmicContrast: 0.8020652448758483
purpose: []
